version: '3.4'
services:
  db:
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_DB=postgres_demo
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    volumes:
      - './db-data:/var/lib/postgresql/data:rw'
    ports:
      - '5432:5432'
